[pytest]
testpaths = tests
python_files = test_*.py
markers =
    gelatto: gelatto related tests
    chatbot: chatbot related tests
    testrail(case_id=None, case_ids=None): map pytest test to TestRail case id(s)
