[pytest]
markers =
    login: login tests
    seg: create segment
    del_seg: delete segment 
    copy_seg: copy segment

# 매번 터미널에 입력하기 귀찮은 옵션들 설정
# -s: print() 내용을 터미널에 출력
# -v: 테스트 결과를 더 자세히 표시
# --disable-warnings: 모든 경고를 숨기고 싶을 때 (위의 markers 등록으로 해결 안 될 때 최후의 수단)
addopts = -s -v