credentials:
  username: "groobee.wjyang102"
  password: "dnwodid7024!"
  
  shop_id: "testywj"
  shop_pw: "groobeegogo34$"

urls:
  admin_page: "https://admin.groobee.io/login"
  shop_page: "https://shop16.grooshop.com/"
  gelatto_page: "https://admin.groobee.io/gelatto/dashboard"
  shop_no: "shop16"

inputs:
  topic: "Honda Motors"
  word: "input_word"
  description: "description"

testrail:
  enabled: true
  base_url: "https://plateerqa.testrail.io"
  user: "wjyang102@plateer.com"

  # 민감정보는 env로 받는 것을 권장
  api_key_env: TESTRAIL_API_KEY

  # Run 생성 규칙
  run:
    name_template: "Gelatto UI - {date} - {marker}"
    id: 65